import React, { useEffect, useState } from 'react';
import { Check, Copy, KeyRound, Loader2, Plus, ShieldX } from 'lucide-react';
import type { Theme } from '../../types';
import { createMachineApiClient, listMachineApiClients, revokeMachineApiClient, type MachineApiClient } from '../../services/userAdministrationService';

const availableScopes = ['locations:read', 'geometry:read', 'leadership:read', 'locations:write', 'leadership:manage', 'audit:read', 'webhooks:manage'];
const ApiClientManagement = ({ theme }: { theme: Theme }) => {
  const [clients, setClients] = useState<MachineApiClient[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [secret, setSecret] = useState(''); const [copied, setCopied] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', description: '', countries: 'UG', scopes: ['locations:read'], rpm: 60, quota: 10000, expiresAt: '' });
  const dark = theme === 'dark'; const panel = dark ? 'border-slate-700 bg-slate-900' : 'border-slate-200 bg-white'; const input = `mt-1.5 h-10 w-full rounded-lg border px-3 text-sm ${dark ? 'border-slate-700 bg-slate-950' : 'border-slate-300 bg-white'}`;
  const load = async () => { try { setClients(await listMachineApiClients()); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load API clients.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const result = await createMachineApiClient({ name: form.name, description: form.description, scopes: form.scopes, assignedCountryCodes: form.countries.split(',').map((value) => value.trim().toUpperCase()).filter(Boolean), requestsPerMinute: form.rpm, dailyQuota: form.quota, expiresAt: form.expiresAt ? new Date(`${form.expiresAt}T23:59:59Z`).toISOString() : undefined }); setSecret(result.apiKey); setForm({ ...form, name: '', description: '' }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create API client.'); } finally { setSaving(false); } };
  const revoke = async (uid: string) => { await revokeMachineApiClient(uid); await load(); };
  return <div className="space-y-4">{error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-500">{error}</p>}{secret && <section className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-5"><h3 className="font-bold text-amber-700 dark:text-amber-300">Copy this key now—it will not be shown again</h3><div className="mt-3 flex gap-2"><code className="min-w-0 flex-1 break-all rounded-lg bg-slate-950 p-3 text-xs text-emerald-400">{secret}</code><button onClick={() => { void navigator.clipboard.writeText(secret); setCopied(true); }} className="rounded-lg bg-yellow-500 px-3 text-slate-950">{copied ? <Check /> : <Copy />}</button></div></section>}
    <form onSubmit={submit} className={`rounded-xl border p-5 ${panel}`}><div className="mb-4 flex items-center gap-2"><Plus size={18} className="text-yellow-500" /><h3 className="font-bold">Create service client</h3></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Client name<input required className={input} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="text-sm font-medium">Country scopes<input className={input} value={form.countries} onChange={(e) => setForm({ ...form, countries: e.target.value })} placeholder="UG, KE" /></label><label className="text-sm font-medium">Requests per minute<input type="number" min="1" max="10000" className={input} value={form.rpm} onChange={(e) => setForm({ ...form, rpm: Number(e.target.value) })} /></label><label className="text-sm font-medium">Daily quota<input type="number" min="1" max="10000000" className={input} value={form.quota} onChange={(e) => setForm({ ...form, quota: Number(e.target.value) })} /></label><label className="text-sm font-medium">Expiry date<input type="date" className={input} value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /></label><label className="text-sm font-medium">Description<input className={input} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div><fieldset className="mt-4"><legend className="text-sm font-medium">Scopes</legend><div className="mt-2 flex flex-wrap gap-2">{availableScopes.map((scope) => <label key={scope} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${dark ? 'border-slate-700' : 'border-slate-300'}`}><input type="checkbox" checked={form.scopes.includes(scope)} onChange={(e) => setForm({ ...form, scopes: e.target.checked ? [...form.scopes, scope] : form.scopes.filter((item) => item !== scope) })} />{scope}</label>)}</div></fieldset><button disabled={saving || !form.scopes.length} className="mt-5 flex h-10 items-center gap-2 rounded-lg bg-yellow-500 px-4 text-sm font-bold text-slate-950 disabled:opacity-50">{saving ? <Loader2 size={16} className="animate-spin" /> : <KeyRound size={16} />} Create API key</button></form>
    <section className={`rounded-xl border p-5 ${panel}`}><h3 className="font-bold">Service clients</h3>{loading ? <Loader2 className="mt-5 animate-spin" /> : <div className="mt-4 space-y-3">{clients.map((client) => <div key={client.uid} className={`flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between ${dark ? 'border-slate-700' : 'border-slate-200'}`}><div><div className="flex items-center gap-2"><span className="font-semibold">{client.name}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${client.status === 'active' ? 'bg-emerald-500/10 text-emerald-500' : 'bg-red-500/10 text-red-500'}`}>{client.status}</span></div><p className="mt-1 font-mono text-xs text-slate-500">al_live_{client.key_prefix}_••••••••</p><p className="mt-1 text-xs text-slate-500">{client.scopes.join(' · ')} · {client.requests_per_minute}/min · {client.daily_quota}/day</p></div>{client.status === 'active' && <button onClick={() => void revoke(client.uid)} className="flex items-center gap-2 rounded-lg border border-red-500/30 px-3 py-2 text-xs font-bold text-red-500"><ShieldX size={15} /> Revoke</button>}</div>)}{clients.length === 0 && <p className="text-sm text-slate-500">No machine clients created.</p>}</div>}</section>
  </div>;
};
export default ApiClientManagement;
